language: cpp

# command to install dependencies
install:
  - sudo add-apt-repository ppa:danmbox/ppa -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install bison
  # install g++ 4.8, if tests are run with g++
  - if [ "`echo $CXX`" == "g++" ]; then sudo apt-get install g++-4.8; fi
  - if [ "`echo $CXX`" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi

compiler:
  - clang
  - gcc

script:
    - make test
