#line 2 "src/various/GrammarLexer.cpp"

#line 4 "src/various/GrammarLexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[217] =
    {   0,
        0,    0,    0,    0,    0,    0,   78,   78,   87,   85,
       68,   69,   85,   77,   58,   43,   44,   56,   40,   53,
       41,   49,   57,    4,    4,   50,   54,   42,   55,   52,
       67,   67,   45,   46,   51,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       47,   85,   48,   71,   72,   76,   75,   76,   76,   78,
       79,   84,   86,   68,   69,   62,   60,   59,   73,   70,
        4,    0,    4,    0,    0,    0,   61,   63,   64,   67,
       67,   67,   67,   67,   25,   67,   67,   67,   67,   67,
       67,   27,   22,   67,   67,   67,   31,   67,   37,   67,

       67,   67,   67,   67,   67,   67,   67,   65,   66,   76,
       76,   74,   78,   82,   83,   80,   81,    4,    5,    1,
        3,    2,   67,   36,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   21,   39,   67,
       18,   67,   16,   67,   67,   67,   67,   38,    0,    1,
        1,    3,    0,    3,    2,    2,    6,   26,   30,   67,
       67,   67,   67,   29,   67,   67,   10,   67,   67,   67,
        7,   67,   67,   11,   20,   28,   35,   67,    0,    5,
        3,   67,   67,   67,   12,   67,   67,   34,   67,   67,
       67,   67,   67,   33,    3,    3,   67,   67,   67,   19,

       17,   23,   67,   67,   67,    8,   32,   15,    9,   67,
       67,   24,   13,   67,   14,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,    1,   21,
       22,   23,    1,   24,   25,   26,   27,   28,   29,   28,
       30,   30,   30,   30,   30,   30,   31,   30,   30,   30,
       30,   32,   33,   30,   30,   30,   30,   34,   30,   30,
       35,   36,   37,    1,   38,    1,   39,   26,   40,   41,

       42,   43,   30,   44,   45,   30,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   55,   56,   57,   30,   58,
       59,   30,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    1,    2,    1,    3,    1,    1,
        4,    1,    1,    1,    1,    1,    5,    5,    5,    1,
        1,    1,    1,    1,    5,    5,    5,    5,    5,    6,
        6,    6,    6,    6,    1,    2,    1,    6,    5,    5,
        5,    5,    5,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    1,
        1,    1
    } ;

static yyconst flex_uint16_t yy_base[225] =
    {   0,
        0,    0,  339,  338,   60,   62,   64,   66,  340,  343,
       72,  336,  316,  343,  343,  343,  343,  343,  343,  343,
      314,  321,   64,   95,   69,  313,  312,  343,  311,  343,
        0,  307,  343,  343,    0,  282,  291,   39,   36,   40,
       49,  287,  278,   48,  288,  270,   36,   53,  276,  274,
      262,  260,  343,  343,  343,   90,  104,  112,  305,    0,
      343,  343,  103,  115,  317,  343,  343,  343,  343,  343,
      114,  106,  120,  123,  125,    0,  343,  343,  343,    0,
      286,  277,  100,   77,    0,  269,  262,   93,  268,  261,
      264,    0,  267,  269,  255,  254,    0,  253,    0,  254,

      259,  253,  259,  261,  246,  260,  247,  343,  343,  142,
      147,  343,    0,  343,  343,  343,  343,  147,  142,  155,
      159,  291,  267,    0,  250,  254,  117,  250,  243,  251,
      128,  244,  237,  251,  249,  233,  234,    0,    0,  241,
        0,  243,    0,  233,  234,  240,  239,    0,  169,  172,
      177,  183,  151,  188,  272,  271,    0,    0,    0,  222,
      228,  219,  221,    0,  235,  231,    0,  230,  224,  215,
      224,  229,  217,    0,    0,    0,    0,  222,  191,  194,
      206,  212,  213,  180,    0,  168,  167,    0,  171,  171,
      176,  148,  149,    0,  209,  212,  142,  152,  151,    0,

        0,    0,  124,  110,   94,    0,    0,    0,    0,   77,
       71,    0,    0,   46,    0,  343,  231,  237,  243,  245,
      251,  257,   63,  261
    } ;

static yyconst flex_int16_t yy_def[225] =
    {   0,
      216,    1,  217,  217,  218,  218,  219,  219,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      220,  220,  216,  216,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      216,  216,  216,  216,  216,  221,  221,  221,  216,  222,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  223,  216,  216,  216,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,

      220,  220,  220,  220,  220,  220,  220,  216,  216,  221,
      221,  216,  222,  216,  216,  216,  216,  216,  216,  216,
      216,  224,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  216,  216,
      216,  216,  216,  216,  224,  224,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  216,  216,
      216,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  216,  216,  220,  220,  220,  220,

      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,    0,  216,  216,  216,  216,
      216,  216,  216,  216
    } ;

static yyconst flex_uint16_t yy_nxt[406] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   10,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   25,   26,
       27,   28,   29,   30,   31,   31,   32,   31,   31,   31,
       31,   31,   31,   31,   33,   10,   34,   35,   36,   37,
       38,   39,   40,   31,   41,   31,   42,   31,   43,   44,
       45,   31,   46,   47,   48,   49,   31,   50,   31,   51,
       52,   53,   57,   58,   57,   58,   61,  122,   61,   62,
       59,   62,   59,   64,   69,   64,   71,  102,   89,   70,
       84,  103,   87,   72,   88,   73,   73,   73,   85,   90,
       97,   92,  111,  111,   86,   91,  104,   93,   98,   63,

       99,   63,   71,   94,  215,  105,  111,  111,  114,   72,
      115,   73,   73,   73,  111,  111,   64,  214,   64,  127,
       74,   71,  119,  119,  119,  213,   75,   71,   76,  128,
      118,  118,  118,  131,   72,  212,   73,   73,   73,  120,
      120,  121,  121,  121,  111,  111,  125,   75,  132,  111,
      111,  116,   76,  126,   71,  160,  211,  117,  119,  119,
      119,  161,  150,  118,  118,  118,  152,  181,  181,  181,
      149,  151,  151,  210,  153,  154,  154,  154,  165,  150,
      179,  166,  179,  149,  150,  180,  180,  180,  151,  151,
      152,  209,  208,  151,  151,  152,  207,  206,  153,  154,

      154,  154,  205,  153,  154,  154,  154,  180,  180,  180,
      180,  180,  180,  195,  204,  203,  195,  202,  201,  195,
      200,  199,  196,  196,  196,  196,  196,  196,  196,  196,
      196,   54,   54,   54,   54,   54,   54,   56,   56,   56,
       56,   56,   56,   60,   60,   60,   60,   60,   60,   80,
       80,  110,  110,  110,  198,  110,  110,  113,  197,  113,
      113,  113,  113,  156,  194,  156,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  155,  155,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  164,  163,  162,  159,  158,  157,  155,  148,

      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  130,  129,  124,  123,   65,
      112,  109,  108,  107,  106,  101,  100,   96,   95,   83,
       82,   81,   79,   78,   77,   68,   67,   66,   65,  216,
       55,   55,    9,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,

      216,  216,  216,  216,  216
    } ;

static yyconst flex_int16_t yy_chk[406] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    6,    6,    7,  223,    8,    7,
        5,    8,    6,   11,   23,   11,   25,   47,   40,   23,
       38,   47,   39,   25,   39,   25,   25,   25,   38,   40,
       44,   41,   56,   56,   38,   40,   48,   41,   44,    7,

       44,    8,   24,   41,  214,   48,   57,   57,   63,   24,
       63,   24,   24,   24,   58,   58,   64,  211,   64,   84,
       24,   71,   72,   72,   72,  210,   24,   73,   24,   84,
       71,   71,   71,   88,   73,  205,   73,   73,   73,   74,
       74,   75,   75,   75,  110,  110,   83,   24,   88,  111,
      111,   63,   24,   83,  118,  127,  204,   63,  119,  119,
      119,  127,  120,  118,  118,  118,  121,  153,  153,  153,
      119,  120,  120,  203,  121,  121,  121,  121,  131,  150,
      149,  131,  149,  119,  151,  149,  149,  149,  150,  150,
      152,  199,  198,  151,  151,  154,  197,  193,  152,  152,

      152,  152,  192,  154,  154,  154,  154,  179,  179,  179,
      180,  180,  180,  181,  191,  190,  195,  189,  187,  196,
      186,  184,  181,  181,  181,  195,  195,  195,  196,  196,
      196,  217,  217,  217,  217,  217,  217,  218,  218,  218,
      218,  218,  218,  219,  219,  219,  219,  219,  219,  220,
      220,  221,  221,  221,  183,  221,  221,  222,  182,  222,
      222,  222,  222,  224,  178,  224,  173,  172,  171,  170,
      169,  168,  166,  165,  163,  162,  161,  160,  156,  155,
      147,  146,  145,  144,  142,  140,  137,  136,  135,  134,
      133,  132,  130,  129,  128,  126,  125,  123,  122,  107,

      106,  105,  104,  103,  102,  101,  100,   98,   96,   95,
       94,   93,   91,   90,   89,   87,   86,   82,   81,   65,
       59,   52,   51,   50,   49,   46,   45,   43,   42,   37,
       36,   32,   29,   27,   26,   22,   21,   13,   12,    9,
        4,    3,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,

      216,  216,  216,  216,  216
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "obj/src/GrammarLexer.l"
#line 2 "obj/src/GrammarLexer.l"
//  Copyright (c) 2014-2017 CASM Organization
//  All rights reserved.
//  
//  Developed by: Philipp Paulweber
//                Emmanuel Pescosta
//                Florian Hahn
//                https://github.com/casm-lang/libcasm-fe
//  
//  This file is part of libcasm-fe.
//  
//  libcasm-fe is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//  
//  libcasm-fe is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//  
//  You should have received a copy of the GNU General Public License
//  along with libcasm-fe. If not, see <http://www.gnu.org/licenses/>.
//  

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <cstdint>

#include "src/Driver.h"

#include "src/various/GrammarParser.tab.h"

#define YY_DECL yy::Parser::symbol_type yylex(libcasm_fe::Driver& driver )

#undef yywrap
#define yywrap() 1

// The location of the current token.
static yy::location loc;

// driver must be global, because it is needed for YY_INPUT
// defined in src/libsyntax/driver.cpp
extern libcasm_fe::Driver *global_driver;

#define STRBUF_LENGTH 1000
void yyerror(const char *s);
char strbuf[STRBUF_LENGTH];

#define YY_INPUT(buf,result,max_size) { \
  result = global_driver->get_next_chars(buf, max_size); \
  if (  result <= 0  ) \
      result = YY_NULL; \
}

#define yyterminate() return( yy::Parser::make_END(loc) )

// flex uses `register` keyword, which is deprecated in c++11
#pragma GCC diagnostic ignored "-Wdeprecated-register"

/* use debug option for more output */
#define YY_NO_INPUT 1



#line 72 "obj/src/GrammarLexer.l"
    // Code run each time a pattern is matched.
    #define YY_USER_ACTION  loc.columns( yyleng );
#line 703 "src/various/GrammarLexer.cpp"

#define INITIAL 0
#define LCOMMENT 1
#define COMMENT 2
#define STRING 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 75 "obj/src/GrammarLexer.l"


    // Code run each time yylex is called.
    loc.step();


#line 929 "src/various/GrammarLexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 217 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 216 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 81 "obj/src/GrammarLexer.l"
{
    return yy::Parser::make_BINARY( yytext + 2, loc );
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 85 "obj/src/GrammarLexer.l"
{
    return yy::Parser::make_HEXADECIMAL( yytext + 2, loc );
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 89 "obj/src/GrammarLexer.l"
{
    return yy::Parser::make_RATIONAL( yytext + 2, loc );
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 93 "obj/src/GrammarLexer.l"
{
    return yy::Parser::make_INTEGER( yytext, loc );
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 97 "obj/src/GrammarLexer.l"
{
    return yy::Parser::make_FLOATING( yytext, loc );
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_CASM(loc); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 104 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_INIT(loc); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 106 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_OPTION(loc); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 108 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_DERIVED(loc); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 109 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_ENUM(loc); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 111 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_RULE(loc); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 112 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_DUMPS(loc); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 114 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_FUNCTION(loc); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 115 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_INITIALLY(loc); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 116 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_DEFINED(loc); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_SEQ(loc); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 119 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_ENDSEQ(loc); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 120 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_PAR(loc); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 121 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_ENDPAR(loc); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 123 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_SKIP(loc); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 124 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_LET(loc); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 125 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_IN(loc); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 126 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_FORALL(loc); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 127 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_ITERATE(loc); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 128 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_DO(loc); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 129 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_CALL(loc); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 130 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_IF(loc); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 131 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_THEN(loc); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 132 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_ELSE(loc); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 133 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_CASE(loc); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 134 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_OF(loc); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 135 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_DEFAULT(loc); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 137 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_UNDEF(loc); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 138 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_FALSE(loc); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 139 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_TRUE(loc); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 141 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_AND(loc); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 142 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_OR(loc); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 143 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_XOR(loc); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 144 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_NOT(loc); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 146 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_PLUS(loc); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 147 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_MINUS(loc); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 148 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_EQUAL(loc); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 149 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_LPAREN(loc); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 150 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_RPAREN(loc); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 151 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_LSQPAREN(loc); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 152 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_RSQPAREN(loc); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 153 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_LCURPAREN(loc); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 154 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_RCURPAREN(loc); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 155 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_DOT(loc); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 156 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_COLON(loc); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 157 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_UNDERLINE(loc); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 158 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_AT(loc); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 159 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_COMMA(loc); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 160 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_LESSER(loc); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 161 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_GREATER(loc); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 162 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_STAR(loc); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 163 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_SLASH(loc); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 164 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_PERCENT(loc); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 166 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_DOTDOT(loc); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 167 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_ARROW(loc); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 168 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_UPDATE(loc); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 169 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_NEQUAL(loc); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 170 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_LESSEQ(loc); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 171 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_GREATEREQ(loc); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 172 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_SEQ_BRACKET(loc); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 173 "obj/src/GrammarLexer.l"
{ return yy::Parser::make_ENDSEQ_BRACKET(loc); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 177 "obj/src/GrammarLexer.l"
{
    return yy::Parser::make_IDENTIFIER( yytext, loc );
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 181 "obj/src/GrammarLexer.l"
{ /* ignore spaces */
    loc.step();
}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 185 "obj/src/GrammarLexer.l"
{ /* ignore newlines too, but reset yycolumn */
    loc.lines( yyleng );
    loc.step();
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 190 "obj/src/GrammarLexer.l"
{
    BEGIN( LCOMMENT );
    loc.lines( 1 );
    loc.step();
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 195 "obj/src/GrammarLexer.l"

	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 196 "obj/src/GrammarLexer.l"
{
    BEGIN( INITIAL );
}
	YY_BREAK
case YY_STATE_EOF(LCOMMENT):
#line 199 "obj/src/GrammarLexer.l"
{
    BEGIN( INITIAL );
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 203 "obj/src/GrammarLexer.l"
{ /* ignore multi line comments */
    BEGIN( COMMENT );
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 206 "obj/src/GrammarLexer.l"
{
    BEGIN( INITIAL );
}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 209 "obj/src/GrammarLexer.l"

	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 210 "obj/src/GrammarLexer.l"

	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 211 "obj/src/GrammarLexer.l"
{
    printf( "Multiline comment not terminated on line %d", yylineno );
    exit( 2 );
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 216 "obj/src/GrammarLexer.l"
{
    BEGIN( STRING );
    strbuf[0] = '\0';
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 220 "obj/src/GrammarLexer.l"
{ /* eat all tokens */
    strncat( strbuf, yytext, STRBUF_LENGTH - 1 );
}
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 223 "obj/src/GrammarLexer.l"

	YY_BREAK
case 80:
YY_RULE_SETUP
#line 224 "obj/src/GrammarLexer.l"
{
    strncat( strbuf, "\n", STRBUF_LENGTH - 1 );
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 227 "obj/src/GrammarLexer.l"
{
    strncat( strbuf, "\t", STRBUF_LENGTH - 1 );
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 230 "obj/src/GrammarLexer.l"
{
    strncat( strbuf, "\"", STRBUF_LENGTH - 1 );
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 233 "obj/src/GrammarLexer.l"
{
    strncat( strbuf, "\'", STRBUF_LENGTH - 1 );
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 236 "obj/src/GrammarLexer.l"
{
    global_driver->error( loc, "unclosed string",
            libcasm_fe::Codes::SyntaxErrorUnclosedString );
    exit( 1 );
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 241 "obj/src/GrammarLexer.l"
{
    BEGIN( INITIAL );
    return yy::Parser::make_STRING( strbuf, loc );
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 246 "obj/src/GrammarLexer.l"
{
    global_driver->error( loc,
            "unrecognized character '" + std::string( yytext ) + "'",
            libcasm_fe::Codes::SyntaxErrorUnrecognizedCharacter );
    exit( 1 );
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 253 "obj/src/GrammarLexer.l"
ECHO;
	YY_BREAK
#line 1486 "src/various/GrammarLexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 217 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 217 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 216);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 253 "obj/src/GrammarLexer.l"



//  
//  Local variables:
//  mode: c++
//  indent-tabs-mode: nil
//  c-basic-offset: 4
//  tab-width: 4
//  End:
//  vim:noexpandtab:sw=4:ts=4:
//  

