#line 1 "src/various/GrammarLexer.cpp"

#line 3 "src/various/GrammarLexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer libcasm_fe_FlexLexer

#ifdef yyalloc
#define libcasm_fe_alloc_ALREADY_DEFINED
#else
#define yyalloc libcasm_fe_alloc
#endif

#ifdef yyrealloc
#define libcasm_fe_realloc_ALREADY_DEFINED
#else
#define yyrealloc libcasm_fe_realloc
#endif

#ifdef yyfree
#define libcasm_fe_free_ALREADY_DEFINED
#else
#define yyfree libcasm_fe_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext



int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int Lexer::yylex()

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 107
#define YY_END_OF_BUFFER 108
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[291] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      108,  106,   80,   81,   79,   78,  106,   97,   65,   67,
       49,   50,   63,   46,   60,   47,   69,   64,    4,    4,
       55,   61,   48,   62,   59,   82,   82,   51,   52,   66,
       57,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   53,   58,
       54,   83,   87,   86,   85,   87,   87,   87,  107,   89,
       91,  107,  107,  107,   95,   94,   95,  107,  107,  107,
      101,   99,   98,   99,  107,  107,  107,   80,   81,   79,
       78,   73,   70,   68,   92,   88,    4,    0,    4,    0,

        0,    0,   56,   72,   74,   71,   75,   82,   82,   82,
       36,   82,   82,   82,   26,   82,   82,   82,   82,   82,
       82,   82,   27,   82,   22,   82,   82,   82,   31,   42,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   76,   77,   84,    0,    0,   90,    0,    0,   93,
       96,    0,    0,  105,  104,  102,  103,  100,    0,    0,
        4,    5,    1,    3,    2,   82,   41,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   21,   45,   18,   82,   16,   82,   82,
       82,   82,   82,   82,   82,   43,    0,    0,    0,    0,

        0,    1,    1,    3,    0,    3,    2,    2,    6,   30,
       82,   82,   82,   82,   29,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,    7,   82,   82,   10,   20,
       28,   40,   82,   82,   82,   35,    0,    5,    3,   82,
       82,   82,   82,   82,   82,   82,   82,   39,   82,   82,
       33,   82,   82,   82,   82,   38,   11,   37,    3,    3,
       24,   82,   82,   82,   19,   17,   82,   34,   23,   82,
       82,   13,   82,   82,   32,   15,    8,   82,   82,   44,
       82,   25,   82,   14,   82,   82,   12,   82,    9,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    8,    9,    8,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   21,   21,   22,    8,   23,
       24,   25,    8,   26,   27,   28,   29,   30,   31,   30,
       32,   32,   32,   32,   32,   32,   33,   32,   32,   32,
       32,   34,   35,   32,   32,   32,   32,   36,   32,   32,
       37,   38,   39,   40,   41,    8,   42,   28,   43,   44,

       45,   46,   47,   48,   49,   32,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       32,   32,   64,   65,   66,    8,    8,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   68,   68,   68,   68,   68,   68,   68,   68,   68,

       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   70,
       70,   70,   70,   70,   70,   70,   70,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        5,    4,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[298] =
    {   0,
        0,    0,   70,    0,  140,  143,  146,  149,  153,  162,
      488,  489,  485,  483,  481,  479,  459,  489,  489,  489,
      489,  489,  489,  489,  489,  457,  464,  135,  216,  151,
      151,  456,  454,  454,  489,    0,  450,  489,  489,  489,
        0,  121,  103,  113,  125,  135,  422,  134,  430,  420,
      135,  431,  412,  140,  146,  143,  134,  417,  405,  403,
      489,  489,  489,  489,  489,  401,  400,  399,  489,  489,
      489,  398,  397,  396,  489,  489,  444,  394,  393,  392,
      489,  489,  489,  190,  391,  390,  389,  453,  451,  449,
      447,  489,  489,  489,  489,  489,  219,  185,  236,  179,

      239,    0,  489,  489,  489,  489,  489,    0,  416,  406,
        0,  391,  394,  188,    0,  389,  181,  397,  394,  387,
      390,  391,    0,  386,  193,  395,  380,  379,    0,    0,
      380,  385,  379,  385,  388,  372,  387,  381,  380,  369,
      370,  489,  489,  489,  359,  358,  489,  357,  356,  489,
      489,  355,  354,  489,  489,  489,  489,  489,  353,  352,
      251,  243,  256,  271,  408,  384,    0,  371,  361,  178,
      365,  368,  193,  360,  353,  352,  367,  365,  363,  214,
      347,  363,  347,    0,    0,    0,  358,    0,  347,  348,
      355,  354,  345,  346,  348,    0,  328,  327,  326,  325,

      264,  267,  283,  286,  278,  290,  381,  380,    0,    0,
      331,  328,  334,  325,    0,  343,  339,  338,  323,  336,
      329,  320,  320,  328,  319,    0,  318,  332,    0,    0,
        0,    0,  327,  325,  326,    0,  293,  296,  308,  325,
      318,  323,  322,  309,  309,  307,  305,    0,  311,  312,
        0,  315,  295,  277,  266,    0,    0,    0,  311,  314,
        0,  264,  278,  276,    0,    0,  277,    0,    0,  247,
      237,    0,  252,  237,    0,    0,    0,  210,  214,    0,
      194,    0,  175,    0,  148,  148,    0,  131,    0,  489,
      335,  340,  345,  347,  352,  138,  355

    } ;

static const flex_int16_t yy_def[298] =
    {   0,
      290,    1,  290,    3,  291,  291,  292,  292,  293,  293,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  294,  294,  290,  290,  290,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  295,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  296,  290,  290,  290,  290,  290,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  297,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  297,  297,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  290,  290,  290,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  290,  290,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,    0,
      290,  290,  290,  290,  290,  290,  290

    } ;

static const flex_int16_t yy_nxt[560] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   12,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       30,   31,   32,   33,   34,   35,   36,   36,   37,   36,
       36,   36,   36,   36,   36,   36,   38,   12,   39,   40,
       41,   42,   43,   44,   45,   46,   36,   47,   48,   36,
       49,   36,   50,   51,   52,   36,   53,   54,   55,   56,
       36,   57,   58,   59,   60,   61,   12,   62,   62,   62,
       63,   63,   64,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   65,   65,
       65,   63,   63,   63,   63,   63,   65,   65,   65,   65,

       65,   65,   65,   65,   65,   65,   63,   63,   63,   63,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   63,   63,   63,   63,   66,   67,   68,
       69,  165,   71,   69,  112,   71,   69,   95,   76,   69,
      113,   76,   96,   69,   69,   81,   69,  114,   77,   83,
       97,   77,   69,   69,   81,   69,  115,   98,   83,   99,
       99,   99,  103,  110,  104,  116,  119,  117,  111,  123,
      129,  139,  140,  289,  133,  124,  125,  118,  120,  134,
       84,  130,  126,  135,  121,  137,  155,  163,  163,   84,

      138,  288,  136,  162,  162,  162,  287,   72,   73,   74,
       72,   73,   74,   78,   79,   80,   78,   79,   80,  212,
       85,   86,   87,  286,  173,   97,  213,  155,   97,   85,
       86,   87,   98,  170,   99,   99,   99,  161,  161,  161,
      174,  181,  156,  100,  171,   97,  285,  216,  157,  101,
      217,  102,   98,  182,   99,   99,   99,  164,  164,  164,
       97,  162,  162,  162,  224,  202,  284,  225,  283,  161,
      161,  161,  101,  201,  203,  203,  202,  237,  102,  237,
      204,  282,  238,  238,  238,  203,  203,  201,  205,  206,
      206,  206,  202,  281,  280,  204,  239,  239,  239,  204,

      279,  203,  203,  205,  206,  206,  206,  205,  206,  206,
      206,  238,  238,  238,  238,  238,  238,  259,  278,  277,
      259,  276,  275,  259,  274,  273,  260,  260,  260,  260,
      260,  260,  260,  260,  260,   70,   70,   70,   70,   70,
       75,   75,   75,   75,   75,   82,   82,   82,   82,   82,
      108,  108,  154,  272,  154,  154,  154,  208,  208,  271,
      270,  269,  268,  267,  266,  265,  264,  263,  262,  261,
      258,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  207,
      207,  158,  151,  147,  144,  236,  235,  234,  233,  232,

      231,  230,  229,  228,  227,  226,  223,  222,  221,  220,
      219,  218,  215,  214,  211,  210,  209,  207,  200,  158,
      199,  151,  198,  147,  197,  144,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      180,  179,  178,  177,  176,  175,  172,  169,  168,  167,
      166,   91,   90,   89,   88,  160,  159,  158,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  142,
      141,  132,  131,  128,  127,  122,  109,  107,  106,  105,
       94,   93,   92,   91,   90,   89,   88,  290,   11,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290
    } ;

static const flex_int16_t yy_chk[560] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        5,  296,    5,    6,   43,    6,    7,   28,    7,    8,
       43,    8,   28,    9,    9,    9,    9,   44,    7,    9,
       30,    8,   10,   10,   10,   10,   44,   30,   10,   30,
       30,   30,   31,   42,   31,   45,   46,   45,   42,   48,
       51,   57,   57,  288,   54,   48,   48,   45,   46,   54,
        9,   51,   48,   55,   46,   56,   84,  100,  100,   10,

       56,  286,   55,   98,   98,   98,  285,    5,    5,    5,
        6,    6,    6,    7,    7,    7,    8,    8,    8,  170,
        9,    9,    9,  283,  117,   29,  170,   84,   97,   10,
       10,   10,   29,  114,   29,   29,   29,   97,   97,   97,
      117,  125,   84,   29,  114,   99,  281,  173,   84,   29,
      173,   29,   99,  125,   99,   99,   99,  101,  101,  101,
      161,  162,  162,  162,  180,  163,  279,  180,  278,  161,
      161,  161,   29,  162,  163,  163,  202,  201,   29,  201,
      164,  274,  201,  201,  201,  202,  202,  162,  164,  164,
      164,  164,  203,  273,  271,  204,  205,  205,  205,  206,

      270,  203,  203,  204,  204,  204,  204,  206,  206,  206,
      206,  237,  237,  237,  238,  238,  238,  239,  267,  264,
      259,  263,  262,  260,  255,  254,  239,  239,  239,  259,
      259,  259,  260,  260,  260,  291,  291,  291,  291,  291,
      292,  292,  292,  292,  292,  293,  293,  293,  293,  293,
      294,  294,  295,  253,  295,  295,  295,  297,  297,  252,
      250,  249,  247,  246,  245,  244,  243,  242,  241,  240,
      235,  234,  233,  228,  227,  225,  224,  223,  222,  221,
      220,  219,  218,  217,  216,  214,  213,  212,  211,  208,
      207,  200,  199,  198,  197,  195,  194,  193,  192,  191,

      190,  189,  187,  183,  182,  181,  179,  178,  177,  176,
      175,  174,  172,  171,  169,  168,  166,  165,  160,  159,
      153,  152,  149,  148,  146,  145,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  128,  127,  126,
      124,  122,  121,  120,  119,  118,  116,  113,  112,  110,
      109,   91,   90,   89,   88,   87,   86,   85,   80,   79,
       78,   77,   74,   73,   72,   68,   67,   66,   60,   59,
       58,   53,   52,   50,   49,   47,   37,   34,   33,   32,
       27,   26,   17,   16,   15,   14,   13,   11,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,

      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  290,  290,  290,  290,  290
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "obj/src/GrammarLexer.l"
#line 2 "obj/src/GrammarLexer.l"
//
//  Copyright (C) 2014-2019 CASM Organization <https://casm-lang.org>
//  All rights reserved.
//
//  Developed by: Philipp Paulweber
//                Emmanuel Pescosta
//                Florian Hahn
//                Ioan Molnar
//                <https://github.com/casm-lang/libcasm-fe>
//
//  This file is part of libcasm-fe.
//
//  libcasm-fe is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  libcasm-fe is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with libcasm-fe. If not, see <http://www.gnu.org/licenses/>.
//
//  Additional permission under GNU GPL version 3 section 7
//
//  libcasm-fe is distributed under the terms of the GNU General Public License
//  with the following clarification and special exception: Linking libcasm-fe
//  statically or dynamically with other modules is making a combined work
//  based on libcasm-fe. Thus, the terms and conditions of the GNU General
//  Public License cover the whole combination. As a special exception,
//  the copyright holders of libcasm-fe give you permission to link libcasm-fe
//  with independent modules to produce an executable, regardless of the
//  license terms of these independent modules, and to copy and distribute
//  the resulting executable under terms of your choice, provided that you
//  also meet, for each linked independent module, the terms and conditions
//  of the license of that module. An independent module is a module which
//  is not derived from or based on libcasm-fe. If you modify libcasm-fe, you
//  may extend this exception to your version of the library, but you are
//  not obliged to do so. If you do not wish to do so, delete this exception
//  statement from your version.
//

#include <libcasm-fe/Codes>
#include <libcasm-fe/Logger>
#include <libcasm-fe/ast/Span>

#include "various/GrammarToken.h"

#include <libstdhl/SourceLocation>
#include <libstdhl/Unicode>

using namespace libcasm_fe;

#undef YY_DECL
#define YY_DECL Parser::symbol_type Lexer::nextToken()

#define yyterminate() return( Parser::make_END(m_loc) )

// Code run each time a pattern is matched.
#define YY_USER_ACTION m_loc.columns( yyleng );

// Code run each time a token is matched, see GrammarToken.hpp.
#define YY_TOKEN_ACTION( TOKEN ) \
    const auto token = Ast::make< Ast::Token >( m_loc, Grammar::Token:: TOKEN ); \
    token->setSpans( fetchSpansAndReset() ); \
    return Parser::make_##TOKEN( token, m_loc );

#line 710 "src/various/GrammarLexer.cpp"
#define YY_NO_INPUT 1
/* %option debug */

#line 714 "src/various/GrammarLexer.cpp"

#define INITIAL 0
#define YY_IDENTIFIER 1
#define YY_INLINE_COMMENT 2
#define YY_BLOCK_COMMENT 3
#define YY_STRING 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 88 "obj/src/GrammarLexer.l"


#line 91 "obj/src/GrammarLexer.l"
    // Code run each time yylex is called.
    m_loc.step();


#line 858 "src/various/GrammarLexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 291 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 290 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 95 "obj/src/GrammarLexer.l"
{
    // BINARY
    ValueLiteral::Ptr valueLiteral = nullptr;
    try
    {
        const auto value = libstdhl::Memory::get< libcasm_ir::BinaryConstant >( yytext + 2, libstdhl::Type::BINARY );
        valueLiteral = Ast::make< ValueLiteral >( m_loc, value );
        valueLiteral->setSpans( fetchSpansAndReset() );
        valueLiteral->setRadix( libstdhl::Type::Radix::BINARY );
    }
    catch( const std::domain_error& e )
    {
        throw Parser::syntax_error( m_loc, e.what() );
    }
    return Parser::make_BINARY( valueLiteral, m_loc );
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 112 "obj/src/GrammarLexer.l"
{
    // HEXADECIMAL
    ValueLiteral::Ptr valueLiteral = nullptr;
    try
    {
        const auto value = libstdhl::Memory::get< libcasm_ir::BinaryConstant >( yytext + 2, libstdhl::Type::HEXADECIMAL );
        valueLiteral = Ast::make< ValueLiteral >( m_loc, value );
        valueLiteral->setSpans( fetchSpansAndReset() );
        valueLiteral->setRadix( libstdhl::Type::Radix::HEXADECIMAL );
    }
    catch( const std::domain_error& e )
    {
        throw Parser::syntax_error( m_loc, e.what() );
    }
    return Parser::make_HEXADECIMAL( valueLiteral, m_loc );
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 129 "obj/src/GrammarLexer.l"
{
    // RATIONAL
    ValueLiteral::Ptr valueLiteral = nullptr;
    try
    {
        const auto value = libstdhl::Memory::get< libcasm_ir::RationalConstant >( yytext + 2 );
        valueLiteral = Ast::make< ValueLiteral >( m_loc, value );
        valueLiteral->setSpans( fetchSpansAndReset() );

    }
    catch( const std::domain_error& e )
    {
        throw Parser::syntax_error( m_loc, e.what() );
    }
    return Parser::make_RATIONAL( valueLiteral, m_loc );
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 146 "obj/src/GrammarLexer.l"
{
    // INTEGER
    ValueLiteral::Ptr valueLiteral = nullptr;
    try
    {
        const auto value = libstdhl::Memory::get< libcasm_ir::IntegerConstant >( yytext, libstdhl::Type::DECIMAL );
        valueLiteral = Ast::make< ValueLiteral >( m_loc, value );
        valueLiteral->setSpans( fetchSpansAndReset() );
    }
    catch( const std::domain_error& e )
    {
        throw Parser::syntax_error( m_loc, e.what() );
    }
    return Parser::make_INTEGER( valueLiteral, m_loc );
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 162 "obj/src/GrammarLexer.l"
{
    // DECIMAL
    ValueLiteral::Ptr valueLiteral = nullptr;
    try
    {
        const auto value = libstdhl::Memory::get< libcasm_ir::DecimalConstant >( yytext );
        valueLiteral = Ast::make< ValueLiteral >( m_loc, value );
        valueLiteral->setSpans( fetchSpansAndReset() );

    }
    catch( const std::domain_error& e )
    {
        throw Parser::syntax_error( m_loc, e.what() );
    }
    return Parser::make_DECIMAL( valueLiteral, m_loc );
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 179 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( CASM ) }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 180 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( INIT ) }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 181 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( DERIVED ) }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 182 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( ENUMERATION ) }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 183 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( RULE ) }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 184 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( USING ) }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 185 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( INVARIANT ) }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 186 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( IMPORT ) }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 187 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( FUNCTION ) }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 188 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( DEFINED ) }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 189 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( SEQ ) }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 190 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( ENDSEQ ) }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 191 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( PAR ) }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 192 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( ENDPAR ) }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 193 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( SKIP ) }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 194 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( LET ) }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 195 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( IN ) }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 196 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( FORALL ) }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 197 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( CHOOSE ) }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 198 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( ITERATE ) }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 199 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( DO ) }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 200 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( IF ) }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 201 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( THEN ) }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 202 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( ELSE ) }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 203 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( CASE ) }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 204 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( OF ) }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 205 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( DEFAULT ) }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 206 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( HOLDS ) }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 207 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( EXISTS ) }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 208 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( WITH ) }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 209 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( AS ) }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 210 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( WHILE ) }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 211 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( UNDEF ) }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 212 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( FALSE ) }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 213 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( TRUE ) }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 214 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( AND ) }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 215 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( OR ) }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 216 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( XOR ) }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 217 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( IMPLIES ) }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 218 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( NOT ) }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 219 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( PLUS ) }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 220 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( MINUS ) }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 221 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( EQUAL ) }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 222 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( LPAREN ) }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 223 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( RPAREN ) }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 224 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( LSQPAREN ) }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 225 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( RSQPAREN ) }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 226 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( LCURPAREN ) }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 227 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( RCURPAREN ) }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 228 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( COLON ) }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 229 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( DOUBLECOLON ) }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 230 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( UNDERLINE ) }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 231 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( VERTICAL_BAR ) }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 232 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( AT ) }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 233 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( COMMA ) }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 234 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( LESSER ) }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 235 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( GREATER ) }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 236 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( ASTERIX ) }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 237 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( SLASH ) }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 238 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( PERCENT ) }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 239 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( CARET ) }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 240 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( MARK ) }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 241 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( DOTDOT ) }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 242 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( DOT ) }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 243 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( MAPS ) }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 244 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( ARROW ) }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 245 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( UPDATE ) }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 246 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( NEQUAL ) }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 247 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( LESSEQ ) }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 248 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( GREATEREQ ) }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 249 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( SEQ_BRACKET ) }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 250 "obj/src/GrammarLexer.l"
{ YY_TOKEN_ACTION( ENDSEQ_BRACKET ) }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 252 "obj/src/GrammarLexer.l"
{ // space
    const auto span = Ast::make< Span >( m_loc, Grammar::Span::SPACE, yyleng);
    m_spans->add(span);
    m_loc.step();
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 258 "obj/src/GrammarLexer.l"
{ // carriage return
    m_loc.step();
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 262 "obj/src/GrammarLexer.l"
{ // tabulator
    const auto span = Ast::make< Span >( m_loc, Grammar::Span::TABULATOR, yyleng );
    m_spans->add(span);
    m_loc.step();
}
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 268 "obj/src/GrammarLexer.l"
{ // newline
    m_loc.lines( yyleng );
    const auto span = Ast::make< Span >( m_loc, Grammar::Span::NEWLINE, yyleng );
    m_spans->add(span);
    m_loc.step();
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 275 "obj/src/GrammarLexer.l"
{
    // ASCII identifier characters START
    m_strbuf.clear();
    m_strbuf.append( yytext );

    const auto nextCharacter = yyinput();
    if( nextCharacter )
    {
        unput( nextCharacter );
    }

    if( libstdhl::Unicode::UTF8::byteSequenceLengthIndication( nextCharacter ) > 1 )
    {
        BEGIN( YY_IDENTIFIER );
    }
    else
    {
        const auto identifier = Ast::make< Identifier >( m_loc, m_strbuf );
        identifier->setSpans( fetchSpansAndReset() );
        return Parser::make_IDENTIFIER( identifier, m_loc );
    }
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 298 "obj/src/GrammarLexer.l"
{
    // UTF-8 identifier character START
    m_strbuf.clear();
    m_loc.columns( -yyleng );
    unput( yytext[ 0 ] );
    BEGIN( YY_IDENTIFIER );
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 306 "obj/src/GrammarLexer.l"
{
    // UTF-8 (byte length 2, 3, and 4) character
    m_loc.columns( -yyleng+1 );
    try
    {
        checkUTF8( yytext );
    }
    catch( const std::domain_error& e )
    {
        BEGIN( INITIAL );
        throw Parser::syntax_error( m_loc, e.what() );
    }
    m_strbuf.append( yytext );
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 321 "obj/src/GrammarLexer.l"
{
    // ASCII characters
    m_strbuf.append( yytext );
}
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 326 "obj/src/GrammarLexer.l"
{
    const auto identifier = Ast::make< Identifier >( m_loc, m_strbuf );
    identifier->setSpans( fetchSpansAndReset() );
    const auto token = Parser::make_IDENTIFIER( identifier, m_loc );
    unput( yytext[0] );
    BEGIN( INITIAL );
    return token;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 335 "obj/src/GrammarLexer.l"
{
    // invalid identifier character detected, unput and return identifier token
    m_loc.columns( -yyleng );
    unput( yytext[0] );
    BEGIN( INITIAL );
    const auto identifier = Ast::make< Identifier >( m_loc, m_strbuf );
    identifier->setSpans( fetchSpansAndReset() );
    return Parser::make_IDENTIFIER( identifier, m_loc );
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 345 "obj/src/GrammarLexer.l"
{ // single-line comments
    m_strbuf.clear();
    m_strbuf.append( yytext );
    BEGIN( YY_INLINE_COMMENT );
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 351 "obj/src/GrammarLexer.l"
{
    // restricted extended ASCII or UTF-8 (byte length 1) character
    m_strbuf.append( yytext );
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 356 "obj/src/GrammarLexer.l"
{
    // UTF-8 (byte length 2, 3, and 4) character
    m_loc.columns( -yyleng+1 );
    m_strbuf.append( yytext );
}
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 362 "obj/src/GrammarLexer.l"
{
    m_loc.lines( yyleng );
    m_strbuf.append( yytext );
    const auto firstCharacter = yyinput();
    if( firstCharacter != '/' )
    {
        if( firstCharacter )
        {
            unput( firstCharacter );
        }

        const auto span = Ast::make< Span >( m_loc, Grammar::Span::INLINE_COMMENT, m_strbuf.length() );
        m_spans->add( span );
        m_loc.step();
        BEGIN( INITIAL );
    }
    else
    {
        const auto secondCharacter = yyinput();
        if( secondCharacter != '/' )
        {
            unput( secondCharacter );
            unput( firstCharacter );
            const auto span = Ast::make< Span >( m_loc, Grammar::Span::INLINE_COMMENT, m_strbuf.length() );
            m_spans->add( span );
            m_loc.step();
            BEGIN( INITIAL );
        }
        else
        {
            m_strbuf.append( std::to_string( firstCharacter ));
            m_strbuf.append( std::to_string( secondCharacter ));
        }
    }
}
	YY_BREAK
case YY_STATE_EOF(YY_INLINE_COMMENT):
#line 398 "obj/src/GrammarLexer.l"
{
    const auto span = Ast::make< Span >( m_loc, Grammar::Span::INLINE_COMMENT, m_strbuf.length() );
    m_spans->add(span);
    BEGIN( INITIAL );
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 404 "obj/src/GrammarLexer.l"
{ // block comments
    m_strbuf.clear();
    m_strbuf.append( yytext );
    BEGIN( YY_BLOCK_COMMENT );
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 410 "obj/src/GrammarLexer.l"
{
    m_strbuf.append( yytext );
    const auto span = Ast::make< Span >( m_loc, Grammar::Span::BLOCK_COMMENT, m_strbuf.length() );
    m_spans->add(span);
    m_loc.step();
    BEGIN( INITIAL );
}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 418 "obj/src/GrammarLexer.l"
{
    m_strbuf.append( yytext );
    m_loc.lines( yyleng );
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 423 "obj/src/GrammarLexer.l"
{
    // restricted extended ASCII or UTF-8 (byte length 1) character
    m_strbuf.append( yytext );
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 428 "obj/src/GrammarLexer.l"
{
    // UTF-8 (byte length 2, 3, and 4) character
    m_loc.columns( -yyleng+1 );
    m_strbuf.append( yytext );
}
	YY_BREAK
case YY_STATE_EOF(YY_BLOCK_COMMENT):
#line 434 "obj/src/GrammarLexer.l"
{
    m_log.error( {m_loc}, "multiline comment not terminated", Code::SyntaxErrorUnclosedComment );
    BEGIN( INITIAL );
    yyterminate();
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 440 "obj/src/GrammarLexer.l"
{ // strings
    m_strbuf.clear();
    BEGIN( YY_STRING );
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 445 "obj/src/GrammarLexer.l"
{
    BEGIN( INITIAL );
    ValueLiteral::Ptr valueLiteral = nullptr;
    try
    {
        const auto value = libstdhl::Memory::get< libcasm_ir::StringConstant >( m_strbuf );
        valueLiteral = Ast::make< ValueLiteral >( m_loc, value );
        valueLiteral->setSpans( fetchSpansAndReset() );
    }
    catch( const std::domain_error& e )
    {
        throw Parser::syntax_error( m_loc, e.what() );
    }
    return Parser::make_STRING( valueLiteral, m_loc );
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 461 "obj/src/GrammarLexer.l"
{
    // restricted extended ASCII or UTF-8 (byte length 1) character without '"' (0x22)
    m_strbuf.append( yytext );
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 466 "obj/src/GrammarLexer.l"
{
    // UTF-8 (byte length 2, 3, and 4) character
    m_loc.columns( -yyleng+1 );
    m_strbuf.append( yytext );
}
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 472 "obj/src/GrammarLexer.l"
{
    m_loc.lines( yyleng );
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 476 "obj/src/GrammarLexer.l"
{
    m_strbuf.append( "\n" );
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 480 "obj/src/GrammarLexer.l"
{
    m_strbuf.append( "\t" );
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 484 "obj/src/GrammarLexer.l"
{
    m_strbuf.append( yytext + 1 );
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 488 "obj/src/GrammarLexer.l"
{
    m_log.error( {m_loc}, "unrecognized escape sequence", Code::SyntaxErrorUnrecognizedCharacter );
}
	YY_BREAK
case YY_STATE_EOF(YY_STRING):
#line 492 "obj/src/GrammarLexer.l"
{
    m_log.error( {m_loc}, "string not terminated", Code::SyntaxErrorUnclosedString );
    BEGIN( INITIAL );
    yyterminate();
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 498 "obj/src/GrammarLexer.l"
{
    m_log.error( {m_loc}, "unrecognized character '" + std::string( yytext ) + "'",
        Code::SyntaxErrorUnrecognizedCharacter );
    m_loc.step();
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 504 "obj/src/GrammarLexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1725 "src/various/GrammarLexer.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(YY_IDENTIFIER):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 291 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 291 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 290);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 504 "obj/src/GrammarLexer.l"


//  
//  Local variables:
//  mode: c++
//  indent-tabs-mode: nil
//  c-basic-offset: 4
//  tab-width: 4
//  End:
//  vim:noexpandtab:sw=4:ts=4:
//  

