#line 1 "src/various/GrammarLexer.cpp"

#line 3 "src/various/GrammarLexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int Lexer::yylex()

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[253] =
    {   0,
        0,    0,    0,    0,    0,    0,   87,   87,   96,   94,
       77,   78,   94,   86,   61,   63,   47,   48,   59,   44,
       56,   45,   65,   60,    4,    4,   53,   57,   46,   58,
       55,   76,   76,   49,   50,   62,   54,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   51,   94,   52,   80,   81,   85,
       84,   85,   85,   87,   88,   93,   95,   77,   78,   69,
       66,   64,   82,   79,    4,    0,    4,    0,    0,    0,
        0,   68,   70,   67,   71,   76,    0,   76,   76,   35,
       76,   76,   76,   25,   76,   76,   76,   76,   76,   76,

       76,   26,   76,   21,   76,   76,   76,   30,   40,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   72,
       73,   85,   85,   83,   87,   92,   91,   89,   90,    4,
        5,    1,    3,    2,   75,    0,   76,   39,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   20,   43,   17,   76,   15,   76,   76,
       76,   76,   76,   76,   41,    0,    1,    1,    3,    0,
        3,    2,    2,   75,   74,    6,   29,   76,   76,   76,
       76,   28,   76,   76,   76,   76,   76,   76,   76,   76,
       76,    7,   76,   10,   19,   27,   38,   76,   76,   34,

        0,    5,    3,   74,   76,   76,   76,   76,   76,   76,
       76,   76,   37,   76,   76,   32,   76,   76,   76,   36,
       11,    3,    3,   23,   76,   76,   76,   18,   16,   76,
       33,   22,   76,   76,   76,   76,   31,   14,    8,   76,
       76,   42,   76,   24,   76,   12,   76,   76,   13,   76,
        9,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,    1,   21,
       22,   23,    1,   24,   25,   26,   27,   28,   29,   28,
       30,   30,   30,   30,   30,   30,   31,   30,   30,   30,
       30,   32,   33,   30,   30,   30,   30,   34,   30,   30,
       35,   36,   37,   38,   39,    1,   40,   26,   41,   42,

       43,   44,   45,   46,   47,   30,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
       62,   30,   63,   64,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    4,    1,    1,
        5,    1,    1,    1,    1,    1,    6,    6,    6,    7,
        1,    1,    1,    1,    8,    8,    8,    8,    8,    9,
        9,    9,    9,    9,    1,    3,    1,    1,    9,    8,
        8,    8,    8,    8,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    1,    1,    1
    } ;

static const flex_int16_t yy_base[266] =
    {   0,
        0,    0,  553,  552,   63,   65,   67,   69,  554,  557,
       75,  550,  530,  557,  557,  557,  557,  557,  557,  557,
      557,  528,  535,   67,   98,   72,   62,  527,  525,  525,
      557,  526,   61,  557,  557,  557,  525,   51,   68,   75,
       72,   79,   73,   78,   77,   74,   90,  116,   80,  119,
      120,   91,   65,   89,  480,  478,  557,  557,  557,  538,
      557,  537,  524,    0,  557,  557,  137,  142,  536,  557,
      557,  557,  557,  557,  146,  131,  153,  134,  159,    0,
        0,  557,  557,  557,  557,  510,  507,  149,  137,  505,
      135,  138,  140,  500,  154,  160,  161,  163,  165,  166,

      167,  491,  169,  172,  178,  173,  176,  483,  482,  177,
      179,  180,  184,  181,  183,  185,  189,  186,  187,  557,
      557,  492,  489,  557,    0,  557,  557,  557,  557,  221,
      227,  240,  243,  451,    0,    0,  194,  438,  206,  195,
      232,  203,  233,  215,  217,  234,  235,  243,  244,  245,
      246,  249,  253,  437,  436,  435,  254,  434,  257,  258,
      255,  260,  261,  268,  431,  282,  299,  303,  307,  310,
      314,  442,  441,    0,  428,  427,  426,  262,  282,  284,
      285,  423,  273,  299,  314,  316,  317,  318,  319,  321,
      323,  325,  326,  421,  420,  419,  418,  327,  329,  416,

      333,  336,  361,  415,  338,  336,  339,  341,  328,  342,
      343,  344,  414,  345,  348,  413,  366,  367,  355,  412,
      410,  384,  396,  407,  368,  369,  377,  406,  404,  370,
      401,  272,  371,  373,  379,  388,  269,  266,  264,  385,
      386,  193,  396,  191,  397,   84,  398,  400,   81,  402,
       76,  557,  460,  469,  478,  482,  491,  500,  509,  513,
      514,  520,  523,  525,  529
    } ;

static const flex_int16_t yy_def[266] =
    {   0,
      252,    1,  253,  253,  254,  254,  255,  255,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  256,  256,  252,  252,  252,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  252,  252,  252,  252,  252,  257,
      252,  257,  252,  258,  252,  252,  259,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  260,
      261,  252,  252,  252,  252,  256,  252,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  252,
      252,  257,  257,  252,  258,  252,  252,  252,  252,  252,
      252,  252,  252,  262,  263,  264,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  252,  252,  252,  252,  252,
      252,  262,  262,  263,  265,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      252,  252,  252,  265,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  252,  252,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,    0,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252
    } ;

static const flex_int16_t yy_nxt[623] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   26,   27,
       28,   29,   30,   31,   32,   32,   33,   32,   32,   32,
       32,   32,   32,   32,   34,   10,   35,   36,   37,   38,
       39,   40,   41,   42,   32,   43,   44,   32,   45,   32,
       46,   47,   48,   32,   49,   50,   51,   52,   32,   53,
       54,   32,   55,   56,   57,   61,   62,   61,   62,   65,
       87,   65,   66,   63,   66,   63,   68,   73,   68,   75,
       87,   81,   74,   82,   87,   88,   76,   87,   77,   77,
       77,   87,   87,   87,   87,   87,   87,   87,   87,   87,

       87,   89,   67,   87,   67,   75,   90,   91,   87,   87,
       87,  118,   76,   92,   77,   77,   77,   93,   98,  106,
       95,  102,   96,   78,  101,  107,   94,  103,  104,   79,
       99,   80,   97,  108,  105,   87,  100,  111,   87,   87,
      119,  116,  127,   68,  109,   68,  117,  131,  131,  131,
      132,  132,   79,   75,   87,  110,   87,   87,   80,   87,
       75,  112,  130,  130,  130,  114,  113,   76,   87,   77,
       77,   77,  127,   87,  115,  133,  133,  133,  138,   87,
       87,  137,   87,  141,   87,   87,   87,  128,   87,  140,
      139,   87,   87,  129,  142,   87,   87,   87,   87,   87,

       87,  144,   87,   87,   87,   87,   87,  146,   87,  143,
       87,  147,   87,   87,   87,  150,  149,  145,  152,  148,
      153,  151,   87,  160,  176,   87,  162,  157,   75,  154,
      159,  156,  155,  158,   87,  163,   87,  130,  130,  130,
      161,  165,  164,  131,  131,  131,  178,  167,  177,  181,
      169,   87,   87,   87,   87,  166,  168,  168,  170,  171,
      171,  171,   87,   87,   87,   87,  185,  183,   87,  166,
      184,  179,   87,   87,   87,  182,   87,   87,  180,   87,
       87,   87,  188,   87,  189,   87,  190,   87,   87,  186,
      187,   87,   87,  201,  191,  201,  194,  197,  202,  202,

      202,   87,  198,   87,   87,  192,  167,  193,  196,  195,
      167,  199,  209,  200,  169,  168,  168,  205,   87,  168,
      168,  169,  170,  171,  171,  171,  203,  203,  203,  170,
      171,  171,  171,   87,  207,   87,   87,   87,   87,  206,
       87,  210,   87,  208,   87,   87,   87,   87,   87,  202,
      202,  202,  202,  202,  202,   87,  211,   87,   87,  213,
       87,   87,   87,   87,   87,  219,  214,   87,  222,  217,
      220,  218,  212,  221,   87,  215,  216,  223,  223,  223,
      224,  226,  228,  227,  225,   87,   87,   87,   87,   87,
       87,  222,   87,  232,  233,  229,   87,  230,   87,  231,

      223,  223,  223,  222,   87,   87,  235,   87,  234,  240,
      238,  236,  223,  223,  223,   87,   87,   87,  239,   87,
       87,   87,  241,   87,  237,   87,   87,  243,  242,   87,
      244,   87,   87,   87,   87,   87,  246,   87,   87,   87,
       87,  245,   87,  248,  247,   87,   87,   87,  172,  172,
       87,  250,  251,   87,   87,   87,   87,   87,  172,  249,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   86,   86,   86,
       86,  122,  123,  122,  122,  123,  122,  122,  122,  122,

      125,   87,   87,  125,  125,  125,  125,  125,  125,  126,
       87,  126,  126,  126,  126,  126,  126,  126,  134,   87,
      134,  135,  135,  173,   87,  173,  136,  173,  174,   87,
      174,  174,  175,  175,  204,  204,  204,  204,   69,  124,
      123,  123,  121,  120,   87,   87,   85,   84,   83,   72,
       71,   70,   69,  252,   59,   59,    9,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252
    } ;

static const flex_int16_t yy_chk[623] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    6,    6,    7,
       38,    8,    7,    5,    8,    6,   11,   24,   11,   26,
       33,   27,   24,   27,   53,   33,   26,   39,   26,   26,
       26,   41,   43,   46,   40,  251,   45,   44,   42,   49,

      249,   38,    7,  246,    8,   25,   38,   39,   54,   47,
       52,   53,   25,   39,   25,   25,   25,   40,   42,   45,
       41,   44,   41,   25,   43,   46,   40,   44,   44,   25,
       42,   25,   41,   47,   44,   48,   42,   49,   50,   51,
       54,   52,   67,   68,   47,   68,   52,   76,   76,   76,
       78,   78,   25,   75,   91,   48,   89,   92,   25,   93,
       77,   50,   75,   75,   75,   51,   50,   77,   88,   77,
       77,   77,   67,   95,   51,   79,   79,   79,   89,   96,
       97,   88,   98,   93,   99,  100,  101,   67,  103,   92,
       91,  104,  106,   67,   93,  107,  110,  105,  111,  112,

      114,   96,  115,  113,  116,  118,  119,   97,  117,   95,
      244,   98,  242,  137,  140,  101,  100,   96,  104,   99,
      105,  103,  142,  114,  137,  139,  116,  111,  130,  106,
      113,  110,  107,  112,  144,  117,  145,  130,  130,  130,
      115,  119,  118,  131,  131,  131,  140,  132,  139,  142,
      133,  141,  143,  146,  147,  131,  132,  132,  133,  133,
      133,  133,  148,  149,  150,  151,  145,  144,  152,  131,
      144,  141,  153,  157,  161,  143,  159,  160,  141,  162,
      163,  178,  148,  239,  149,  238,  150,  164,  237,  146,
      147,  232,  183,  166,  151,  166,  157,  161,  166,  166,

      166,  179,  162,  180,  181,  152,  167,  153,  160,  159,
      168,  163,  183,  164,  169,  167,  167,  178,  184,  168,
      168,  171,  169,  169,  169,  169,  170,  170,  170,  171,
      171,  171,  171,  185,  180,  186,  187,  188,  189,  179,
      190,  184,  191,  181,  192,  193,  198,  209,  199,  201,
      201,  201,  202,  202,  202,  206,  185,  205,  207,  187,
      208,  210,  211,  212,  214,  193,  188,  215,  203,  191,
      198,  192,  186,  199,  219,  189,  190,  203,  203,  203,
      205,  207,  209,  208,  206,  217,  218,  225,  226,  230,
      233,  222,  234,  214,  215,  210,  227,  211,  235,  212,

      222,  222,  222,  223,  240,  241,  218,  236,  217,  230,
      226,  219,  223,  223,  223,  243,  245,  247,  227,  248,
      231,  250,  233,  229,  225,  228,  224,  235,  234,  221,
      236,  220,  216,  213,  204,  200,  241,  197,  196,  195,
      194,  240,  182,  245,  243,  177,  176,  175,  173,  172,
      165,  248,  250,  158,  156,  155,  154,  138,  134,  247,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  256,  256,  256,
      256,  257,  123,  257,  257,  122,  257,  257,  257,  257,

      258,  109,  108,  258,  258,  258,  258,  258,  258,  259,
      102,  259,  259,  259,  259,  259,  259,  259,  260,   94,
      260,  261,  261,  262,   90,  262,   87,  262,  263,   86,
      263,  263,  264,  264,  265,  265,  265,  265,   69,   63,
       62,   60,   56,   55,   37,   32,   30,   29,   28,   23,
       22,   13,   12,    9,    4,    3,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "obj/src/GrammarLexer.l"
#line 2 "obj/src/GrammarLexer.l"
//  Copyright (c) 2014-2017 CASM Organization
//  All rights reserved.
//
//  Developed by: Philipp Paulweber
//                Emmanuel Pescosta
//                Florian Hahn
//                https://github.com/casm-lang/libcasm-fe
//
//  This file is part of libcasm-fe.
//
//  libcasm-fe is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  libcasm-fe is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with libcasm-fe. If not, see <http://www.gnu.org/licenses/>.
//
//  Additional permission under GNU GPL version 3 section 7
//
//  libcasm-fe is distributed under the terms of the GNU General Public License
//  with the following clarification and special exception: Linking libcasm-fe
//  statically or dynamically with other modules is making a combined work
//  based on libcasm-fe. Thus, the terms and conditions of the GNU General
//  Public License cover the whole combination. As a special exception,
//  the copyright holders of libcasm-fe give you permission to link libcasm-fe
//  with independent modules to produce an executable, regardless of the
//  license terms of these independent modules, and to copy and distribute
//  the resulting executable under terms of your choice, provided that you
//  also meet, for each linked independent module, the terms and conditions
//  of the license of that module. An independent module is a module which
//  is not derived from or based on libcasm-fe. If you modify libcasm-fe, you
//  may extend this exception to your version of the library, but you are
//  not obliged to do so. If you do not wish to do so, delete this exception
//  statement from your version.
//

#include "Lexer.h"

#include "Codes.h"
#include "Logger.h"
#include "SourceLocation.h"

using namespace libcasm_fe;

#undef YY_DECL
#define YY_DECL Parser::symbol_type Lexer::nextToken()

#define yyterminate() return( Parser::make_END(loc) )

// Code run each time a pattern is matched.
#define YY_USER_ACTION loc.columns( yyleng );

#line 686 "src/various/GrammarLexer.cpp"
/* %option debug */
#define YY_NO_INPUT 1

#line 690 "src/various/GrammarLexer.cpp"

#define INITIAL 0
#define LCOMMENT 1
#define COMMENT 2
#define STRING 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 77 "obj/src/GrammarLexer.l"


#line 80 "obj/src/GrammarLexer.l"
    // Code run each time yylex is called.
    loc.step();


#line 833 "src/various/GrammarLexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 253 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 252 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 84 "obj/src/GrammarLexer.l"
{
    return Parser::make_BINARY( yytext + 2, loc );
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 88 "obj/src/GrammarLexer.l"
{
    return Parser::make_HEXADECIMAL( yytext + 2, loc );
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 92 "obj/src/GrammarLexer.l"
{
    return Parser::make_RATIONAL( yytext + 2, loc );
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 96 "obj/src/GrammarLexer.l"
{
    return Parser::make_INTEGER( yytext, loc );
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 100 "obj/src/GrammarLexer.l"
{
    return Parser::make_DECIMAL( yytext, loc );
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 106 "obj/src/GrammarLexer.l"
{ return Parser::make_CASM(loc); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 107 "obj/src/GrammarLexer.l"
{ return Parser::make_INIT(loc); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 109 "obj/src/GrammarLexer.l"
{ return Parser::make_DERIVED(loc); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 110 "obj/src/GrammarLexer.l"
{ return Parser::make_ENUMERATION(loc); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 111 "obj/src/GrammarLexer.l"
{ return Parser::make_RULE(loc); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 112 "obj/src/GrammarLexer.l"
{ return Parser::make_USING(loc); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 114 "obj/src/GrammarLexer.l"
{ return Parser::make_FUNCTION(loc); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "obj/src/GrammarLexer.l"
{ return Parser::make_INITIALLY(loc); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 116 "obj/src/GrammarLexer.l"
{ return Parser::make_DEFINED(loc); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 118 "obj/src/GrammarLexer.l"
{ return Parser::make_SEQ(loc); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 119 "obj/src/GrammarLexer.l"
{ return Parser::make_ENDSEQ(loc); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 120 "obj/src/GrammarLexer.l"
{ return Parser::make_PAR(loc); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 121 "obj/src/GrammarLexer.l"
{ return Parser::make_ENDPAR(loc); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 123 "obj/src/GrammarLexer.l"
{ return Parser::make_SKIP(loc); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 124 "obj/src/GrammarLexer.l"
{ return Parser::make_LET(loc); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 125 "obj/src/GrammarLexer.l"
{ return Parser::make_IN(loc); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 126 "obj/src/GrammarLexer.l"
{ return Parser::make_FORALL(loc); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 127 "obj/src/GrammarLexer.l"
{ return Parser::make_CHOOSE(loc); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 128 "obj/src/GrammarLexer.l"
{ return Parser::make_ITERATE(loc); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 129 "obj/src/GrammarLexer.l"
{ return Parser::make_DO(loc); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 130 "obj/src/GrammarLexer.l"
{ return Parser::make_IF(loc); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 131 "obj/src/GrammarLexer.l"
{ return Parser::make_THEN(loc); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 132 "obj/src/GrammarLexer.l"
{ return Parser::make_ELSE(loc); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 133 "obj/src/GrammarLexer.l"
{ return Parser::make_CASE(loc); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 134 "obj/src/GrammarLexer.l"
{ return Parser::make_OF(loc); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 135 "obj/src/GrammarLexer.l"
{ return Parser::make_DEFAULT(loc); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 136 "obj/src/GrammarLexer.l"
{ return Parser::make_HOLDS(loc); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 137 "obj/src/GrammarLexer.l"
{ return Parser::make_EXISTS(loc); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 138 "obj/src/GrammarLexer.l"
{ return Parser::make_WITH(loc); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 139 "obj/src/GrammarLexer.l"
{ return Parser::make_AS(loc); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 141 "obj/src/GrammarLexer.l"
{ return Parser::make_UNDEF(loc); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 142 "obj/src/GrammarLexer.l"
{ return Parser::make_FALSE(loc); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 143 "obj/src/GrammarLexer.l"
{ return Parser::make_TRUE(loc); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 145 "obj/src/GrammarLexer.l"
{ return Parser::make_AND(loc); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 146 "obj/src/GrammarLexer.l"
{ return Parser::make_OR(loc); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 147 "obj/src/GrammarLexer.l"
{ return Parser::make_XOR(loc); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 148 "obj/src/GrammarLexer.l"
{ return Parser::make_IMPLIES(loc); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 149 "obj/src/GrammarLexer.l"
{ return Parser::make_NOT(loc); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 151 "obj/src/GrammarLexer.l"
{ return Parser::make_PLUS(loc); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 152 "obj/src/GrammarLexer.l"
{ return Parser::make_MINUS(loc); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 153 "obj/src/GrammarLexer.l"
{ return Parser::make_EQUAL(loc); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 154 "obj/src/GrammarLexer.l"
{ return Parser::make_LPAREN(loc); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 155 "obj/src/GrammarLexer.l"
{ return Parser::make_RPAREN(loc); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 156 "obj/src/GrammarLexer.l"
{ return Parser::make_LSQPAREN(loc); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 157 "obj/src/GrammarLexer.l"
{ return Parser::make_RSQPAREN(loc); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 158 "obj/src/GrammarLexer.l"
{ return Parser::make_LCURPAREN(loc); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 159 "obj/src/GrammarLexer.l"
{ return Parser::make_RCURPAREN(loc); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 160 "obj/src/GrammarLexer.l"
{ return Parser::make_COLON(loc); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 161 "obj/src/GrammarLexer.l"
{ return Parser::make_UNDERLINE(loc); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 162 "obj/src/GrammarLexer.l"
{ return Parser::make_AT(loc); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 163 "obj/src/GrammarLexer.l"
{ return Parser::make_COMMA(loc); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 164 "obj/src/GrammarLexer.l"
{ return Parser::make_LESSER(loc); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 165 "obj/src/GrammarLexer.l"
{ return Parser::make_GREATER(loc); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 166 "obj/src/GrammarLexer.l"
{ return Parser::make_ASTERIX(loc); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 167 "obj/src/GrammarLexer.l"
{ return Parser::make_SLASH(loc); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 168 "obj/src/GrammarLexer.l"
{ return Parser::make_PERCENT(loc); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 169 "obj/src/GrammarLexer.l"
{ return Parser::make_CARET(loc); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 170 "obj/src/GrammarLexer.l"
{ return Parser::make_MARK(loc); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 172 "obj/src/GrammarLexer.l"
{ return Parser::make_DOTDOT(loc); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 173 "obj/src/GrammarLexer.l"
{ return Parser::make_DOT(loc); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 174 "obj/src/GrammarLexer.l"
{ return Parser::make_MAPS(loc); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 175 "obj/src/GrammarLexer.l"
{ return Parser::make_ARROW(loc); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 176 "obj/src/GrammarLexer.l"
{ return Parser::make_UPDATE(loc); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 177 "obj/src/GrammarLexer.l"
{ return Parser::make_NEQUAL(loc); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 178 "obj/src/GrammarLexer.l"
{ return Parser::make_LESSEQ(loc); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 179 "obj/src/GrammarLexer.l"
{ return Parser::make_GREATEREQ(loc); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 180 "obj/src/GrammarLexer.l"
{ return Parser::make_SEQ_BRACKET(loc); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 181 "obj/src/GrammarLexer.l"
{ return Parser::make_ENDSEQ_BRACKET(loc); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 185 "obj/src/GrammarLexer.l"
{
    return Parser::make_ABSOLUTE_IDENTIFIER_PATH( yytext, loc );
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 189 "obj/src/GrammarLexer.l"
{
    return Parser::make_RELATIVE_IDENTIFIER_PATH( yytext, loc );
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 193 "obj/src/GrammarLexer.l"
{
    return Parser::make_IDENTIFIER( yytext, loc );
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 197 "obj/src/GrammarLexer.l"
{ // ignore spaces
    loc.step();
}
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 201 "obj/src/GrammarLexer.l"
{ // ignore newlines
    loc.lines( yyleng );
    loc.step();
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 206 "obj/src/GrammarLexer.l"
{ // single-line comments
    BEGIN( LCOMMENT );
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 209 "obj/src/GrammarLexer.l"

	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 210 "obj/src/GrammarLexer.l"
{
    BEGIN( INITIAL );
    loc.lines( 1 );
    loc.step();
}
	YY_BREAK
case YY_STATE_EOF(LCOMMENT):
#line 215 "obj/src/GrammarLexer.l"
{
    BEGIN( INITIAL );
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 219 "obj/src/GrammarLexer.l"
{ // multi-line comments
    BEGIN( COMMENT );
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 222 "obj/src/GrammarLexer.l"
{
    BEGIN( INITIAL );
}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 225 "obj/src/GrammarLexer.l"
{
    loc.lines( 1 );
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 228 "obj/src/GrammarLexer.l"

	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 229 "obj/src/GrammarLexer.l"
{
    BEGIN( INITIAL );
    log.error( {loc}, "multiline comment not terminated", Code::SyntaxErrorUnclosedComment );
    yyterminate();
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 235 "obj/src/GrammarLexer.l"
{ // strings
    BEGIN( STRING );
    strbuf.clear();
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 239 "obj/src/GrammarLexer.l"
{ /* eat all tokens */
    strbuf.append( yytext );
}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 242 "obj/src/GrammarLexer.l"
{
    loc.lines( 1 );
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 245 "obj/src/GrammarLexer.l"
{
    strbuf.append( "\n" );
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 248 "obj/src/GrammarLexer.l"
{
    strbuf.append( "\t" );
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 251 "obj/src/GrammarLexer.l"
{
    strbuf.append( yytext + 1 );
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 254 "obj/src/GrammarLexer.l"
{
    log.error( {loc}, "unknown escape sequence", Code::SyntaxErrorUnclosedString );
    yyterminate();
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 258 "obj/src/GrammarLexer.l"
{
    BEGIN( INITIAL );
    log.error( {loc}, "string not terminated", Code::SyntaxErrorUnclosedString );
    yyterminate();
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 263 "obj/src/GrammarLexer.l"
{
    BEGIN( INITIAL );
    return Parser::make_STRING( strbuf, loc );
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 268 "obj/src/GrammarLexer.l"
{
    log.error( {loc}, "unrecognized character `" + std::string( yytext ) + "`",
        Code::SyntaxErrorUnrecognizedCharacter );
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 273 "obj/src/GrammarLexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1442 "src/various/GrammarLexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 253 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 253 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 252);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 273 "obj/src/GrammarLexer.l"


Lexer::Lexer( Logger& log, std::istream& in, std::ostream& out )
: yyFlexLexer( in, out )
, log(log)
, loc()
, strbuf()
{
}

void Lexer::setFileName( const std::string& fileName )
{
    loc.begin.fileName = loc.end.fileName = std::make_shared< std::string >( fileName );
}

void Lexer::LexerError( const char* msg )
{
    log.error( {loc}, msg, Code::SyntaxError );
}

//  
//  Local variables:
//  mode: c++
//  indent-tabs-mode: nil
//  c-basic-offset: 4
//  tab-width: 4
//  End:
//  vim:noexpandtab:sw=4:ts=4:
//  

